function(study_topic name)
    file(GLOB_RECURSE SOURCES CONFIGURE_DEPENDS "${CMAKE_SOURCE_DIR}/topics/${name}/*.cpp")
    if(SOURCES)
        set(exec_name ${name}_tests)
        add_executable(${exec_name} ${SOURCES})
        target_link_libraries(${exec_name} PRIVATE gtest_main)

        include(GoogleTest)
        gtest_discover_tests(${exec_name})
    else()
        message(WARNING "No .cpp files found for study_topic(${name}) in ${CMAKE_CURRENT_SOURCE_DIR}")
    endif()
endfunction()
