function(study_topic name)
    file(GLOB_RECURSE SOURCES CONFIGURE_DEPENDS "${CMAKE_SOURCE_DIR}/topics/${name}/*.cpp")
    if(SOURCES)
        add_executable(${name}_tests ${SOURCES})
        target_link_libraries(${name}_tests PRIVATE gtest_main)
        include(GoogleTest)
        gtest_discover_tests(${name}_tests)
    else()
        message(WARNING "No .cpp files found for study_topic(${name}) in ${CMAKE_CURRENT_SOURCE_DIR}")
    endif()
endfunction()
